### ISSUE TITLE
Refactor to use Confluent client

### ISSUE THREAD

**Issue by marshmallory** [crossplane-contrib/provider-kafka#19]
We have decided to move forward with refactoring the kafka provider to use Confluent's Kafka Go client.  Opening this issue for discussion, questions, concerns, etc.

**Comment by marshmallory** [comment]
We have decided to return to the existing library for now and may pursue the Confluent provider in addition to this or at a later time.

**Comment by sergii-opsfleet** [comment]
@marshmallory does the provider work with confluent's kafka clusters ?

**Comment by admssa** [comment]
@marshmallory does the provider support confluent's Kafka clusters?

**Comment by marshmallory** [comment]
@admssa It should, we just opted not to use their library.  It didn't have all of the features we were interested in.
