### ISSUE TITLE
release first version

### ISSUE THREAD

**Issue by janwillies** [crossplane-contrib/provider-kafka#32]
### What problem are you facing?
there is no release of `provider-kafka` yet. No API documentation shows up at https://doc.crds.dev/github.com/crossplane-contrib/provider-kafka 

### How could Crossplane help solve your problem?
Release a first version, based on https://crossplane.io/docs/v1.7/contributing/release-process.html

**Comment by stevendborrelli** [comment]
Hi @janwillies! I have a [PR](https://github.com/crossplane-contrib/provider-kafka/pull/33) to get testing working in Github actions. Once that is merged we can cut a release.

**Comment by stevendborrelli** [comment]
We've cut a `v0.1.0` release, and CRDs are available at <https://doc.crds.dev/github.com/crossplane-contrib/provider-kafka>. Please reopen this issue if you have any problems. 

```console
kubectl crossplane install provider crossplane/provider-kafka:v0.1.0
```
