### ISSUE TITLE
Support SASL mechanism AWS_MSK_IAM for use with MSK

### ISSUE THREAD

**Issue by mdhwk** [crossplane-contrib/provider-kafka#34]
### What problem are you facing?
Would like to be able to use AWS IAM when authenticating against an MSK cluster.

### How could Crossplane help solve your problem?
Users would be able to attach a role to the provider and therefor follow the same pattern that many other tools use when running in EKS.

I would be happy to make this contribution myself but can't find a contribution doc, so just let me know what approach you like.

**Comment by marshmallory** [comment]
Closing.  Resolved.
