### ISSUE TITLE
ArgoCD-Crossplane: Topic finalizer prevents deletion

### ISSUE THREAD

**Issue by withoutnickname** [crossplane-contrib/provider-kafka#48]
Hi team,

Is there a way to override/remove Topic default finalizer (_finalizer.managedresource.crossplane.io_) declaratively?

The use-case:
ArgoCD cannot remove Topic object after manifest deletion in Git and synchronization never ends:
![image](https://user-images.githubusercontent.com/35262641/203944240-402c3610-3dc7-46ca-9fa8-02abb466135c.png)

If to remove finalizer from Topic's spec manually - all goes as expected immediately.

Already tried:

```
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
```
and
```
metadata:
  finalizers: []
```
but no luck, _finalizer.managedresource.crossplane.io_ finalizer is still added automatically.

crossplane:v1.9.1
provider-kafka-controller:v0.1.0
argocd:v2.4.12

**Comment by jograca** [comment]
This is largely an Argo issue, not for this provider. @withoutnickname contact me and I think we can get to a resolution.
